// Web-build conformance standard exports.
export {
  AaaEvidence,
  type AaaEvidenceType,
  AiReadabilityEvidence,
  type AiReadabilityEvidenceType,
  AxeEvidence,
  type AxeEvidenceType,
  BaselineEvidence,
  type BaselineEvidenceType,
  CogaUsabilityEvidence,
  type CogaUsabilityEvidenceType,
  CommonMarkEvidence,
  type CommonMarkEvidenceType,
  COMPACT_CLAIM,
  type ConformanceArea,
  type ConformanceTier,
  ContentDigestsEvidence,
  type ContentDigestsEvidenceType,
  CoreWebVitalSample,
  type CoreWebVitalSampleType,
  CoreWebVitalsEvidence,
  type CoreWebVitalsEvidenceType,
  CRITERIA,
  type Criterion,
  CWV_THRESHOLDS,
  type EvidenceSource,
  ExternalEvidence,
  type ExternalEvidenceInput,
  type ExternalEvidenceType,
  FeedsEvidence,
  type FeedsEvidenceType,
  HtmlValidatorEvidence,
  type HtmlValidatorEvidenceType,
  HttpRfc9110Evidence,
  type HttpRfc9110EvidenceType,
  IpfsCidEvidence,
  type IpfsCidEvidenceType,
  JsonLdShaclEvidence,
  type JsonLdShaclEvidenceType,
  ManualA11yEvidence,
  type ManualA11yEvidenceType,
  OpenApiEvidence,
  type OpenApiEvidenceType,
  ReliabilityEvidence,
  type ReliabilityEvidenceType,
  ReproducibleBuildEvidence,
  type ReproducibleBuildEvidenceType,
  SbomEvidence,
  type SbomEvidenceType,
  SecurityEvidence,
  type SecurityEvidenceType,
  SeoTechnicalEvidence,
  type SeoTechnicalEvidenceType,
  SignedReleaseManifestEvidence,
  type SignedReleaseManifestEvidenceType,
  SlsaProvenanceEvidence,
  type SlsaProvenanceEvidenceType,
  STANDARD_NAME,
  STANDARD_VERSION,
} from "./web_build.ts";

export {
  conformance,
  type ConformanceAreaSummary,
  type ConformanceReport,
  type ConformanceSummary,
  type CriterionResult,
  type CriterionStatus,
  type LoneFindings,
} from "./conformance.ts";
