// Web-build conformance standard exports.
export {
  AaaEvidence,
  type AaaEvidenceType,
  AxeEvidence,
  type AxeEvidenceType,
  BaselineEvidence,
  type BaselineEvidenceType,
  COMPACT_CLAIM,
  type ConformanceArea,
  CoreWebVitalSample,
  type CoreWebVitalSampleType,
  CoreWebVitalsEvidence,
  type CoreWebVitalsEvidenceType,
  CRITERIA,
  type Criterion,
  CWV_THRESHOLDS,
  type EvidenceSource,
  ExternalEvidence,
  type ExternalEvidenceInput,
  type ExternalEvidenceType,
  HtmlValidatorEvidence,
  type HtmlValidatorEvidenceType,
  ManualA11yEvidence,
  type ManualA11yEvidenceType,
  ReliabilityEvidence,
  type ReliabilityEvidenceType,
  SecurityEvidence,
  type SecurityEvidenceType,
  STANDARD_NAME,
  STANDARD_VERSION,
} from "./web_build.ts";

export {
  conformance,
  type ConformanceReport,
  type ConformanceSummary,
  type CriterionResult,
  type CriterionStatus,
  type LoneFindings,
} from "./conformance.ts";
