name: standard
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  standard:
    uses: bounded-systems/.github/.github/workflows/repo-standard.yml@0b9e3a7657ae1e45b1e9ddfebd4c54f87f68e625
    with:
      security: true
      test: true
      runtime: deno
      test-command: "deno task ci"
